### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by gouinK** [dex-screener/google-sheets#1]
Greetings, is there a way to pull historical data from your API?

For example, I found someone using this type of request, but it is only giving data for the past 15 minutes or so:
`https://io6.dexscreener.io/u/trading-history/recent/{network}/{address}`

Thanks!

**Comment by alexandrebini** [comment]
Hey @gouinK 

The URL you shared is not part of our API. Please check https://docs.dexscreener.com

Unfortunately, right now it is not possible to pull historical data.
